### PR TITLE
fixed an issue with the web interface not loading under docker

### PR DESCRIPTION
**Pull request by koalaeagle**
## Description
This fixes an issue with the web interface not loading when running under docker.

Fixes a sub issue under #210 

## Type of change
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
Please put an `x` in the boxes that apply. You can also fill these out after creating the PR.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have tested this code locally, and it is working as intended
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by andzejsp** [comment]
oh yeah that looks like it, someone forgot that the new UI is server from different folder 🗡️

**Comment by koalaeagle** [comment]
Update - this does close #210. I believe there were multiple issues at play, but based on the last reply this has now helped two (three including myself) people get up and running via docker.

**Review by ParisNeo — APPROVED** [review]
Legit

**Review by ParisNeo — APPROVED** [review]
Legit

**Pull request merged**
