### PR TITLE
Tried to get it working on a phone

### PR DESCRIPTION
**Pull request by okkebal**
Tried to het the UI to work on a phone. At least it WORKS on a phone now.

### CODE REVIEW

**Comment by andzejsp** [comment]
imo this PR needs more work, adding those columns and other stuff breaks the desktop version, to the point where some things are not working the way they used to - scroll to bottom on load discussion, and chatbox is not visible, unless you scroll to the last message in the discussion.

You can use tailwind to dynamically change the classes based on their container size.

**Comment by ParisNeo** [comment]
Thanks for trying. But as andzesp said, we need to make sure that the desktop version works perfectly and use tailwindcss to adapt to other devices. We definitely gonna do a phone version but that shouldn't be at the cost of breaking the desktop version.

**Comment by okkebal** [comment]
The breakpoint was wrong. Can't get it to scroll down indeed. Well. I guess you guys want a different solution, so I stop working on this. I don't know what Tailwind is. Even If I get the Scrolltobottom to work you don't want thsi I guess. 

Just used to a mobile first design. I guess its Desktop first here :)

**Comment by andzejsp** [comment]
Design is not final, still many missing components, so the panels/ divs will jump around, once everything is settled there will be move to a mobile. 

If you can manage add changes so that desktop version doesnt change, then your changes are welcome. At this point your changes break other things. 

Tailwind is css styler, where you dont need to define separate classes for each div, you just write the thing you want the div to do in the class parameter. For more info https://tailwindcss.com/docs/installation.

**Comment by okkebal** [comment]
Well I changed to scrolltobottom function to just scroll to the bottom of the page now.... It works, but its still not perfect.

**Pull request closed without merging**
