### PR TITLE
io socket fix:

### PR DESCRIPTION
**Pull request by dcmumby**
## Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
Please put an `x` in the boxes that apply. You can also fill these out after creating the PR.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have tested this code locally, and it is working as intended
- [ ] I have updated the documentation accordingly

## Screenshots
If applicable, add screenshots to help explain your changes.

### CODE REVIEW

**Comment by dcmumby** [comment]
The socket is now available locally and remotely

**Comment by andzejsp** [comment]
socket fix is already merged in https://github.com/ParisNeo/gpt4all-ui/pull/249 try to pull latest changes. The scripts folder rename is still not fixed

**Comment by andzejsp** [comment]
also please confirm that in your env/ folder there is scripts folder, because in my linux vm there is no such folder. and the activate script is located in env/bin/ folder 

image
image

**Comment by dcmumby** [comment]
I am on linux but the folder does no exist the script runs i just noted a capital "s" which had to be wrong

**Comment by dcmumby** [comment]
Hi paris 

the line should be env/bin/activate 

then it works

**Review by ParisNeo — APPROVED** [review]
legit

**Pull request closed without merging**
